### PR TITLE
Exclude AAL region/ creat ROI

### PR DESCRIPTION
**Pull request by Aisa2**
1. Added function for excluding AAL regions by re-defining the mask. 
2. Added function for making an roi from an AAL area
3. Also added some code to loadAal78 making empty cells into ' ' or 0, to deal with indexing problems.
   (If 3 gets pulled, we can erase redundant code in excludeAALRegion)

-To do: find out how to incorporate the mask into t-maps as well? (currently only displayed for P map; t map becomes green at masked points)

### CODE REVIEW

**Comment by abcdlab-nf** [comment]
- I think that finding region IDs by text search should be a separate function from creating a mask from a region ID
- Maybe [ids] = regionLabelIdsByText(regionLabels, text); and [mask] = maskFromRegionLabelIds(regionLabels, ids); — where ids is a vector of one or more region ID values
- I think the only function that should have any specific notion of "AAL" is loadAal78. Any other function we want to use with AAL should be able to take any structure variable in the format returned by loadAal78 without any assumptions about the number of regions. This allows us to use any other atlas and simply write a loadWhateverAtlas function without having to change any other function.
- Let's call the generic version of aal78 a "regionLabels" variable (like the argument in testModel).
- For that reason, any function that uses a regionLabels set like aal78 should take the regionLabels variable as an argument, rather than calling loadAal78 from within the function.
- As for the non-existent regions in aal_78.regions, it's somewhat by design that that variable is "sparse". I'll have to think more about the best way to address that. The search-by-text usage isn't one I had considered before.

**Comment by abcdlab-nf** [comment]
I made the findRegionIdsByText function. 

Next step is to make its sibling, maskFromRegionIds(regionLabels, regionIds)...

**Comment by Aisa2** [comment]
Took a shot at maskFromRegionIds, let me know what you think!

**Comment by abcdlab-nf** [comment]
Short and sweet! But... I expected the "polarity" to be the opposite! I know you're thinking about this as an approach to excluding regions, but as a general purpose function I think it makes more sense for the function to return true values for vertices that fall in one or more of the regions, and false for all other vertices. That's a more general case. If it would be clearer, we can call the function roiFromRegionIds instead.
Also
- It doesn't currently return logical values, it returns numeric values.
- In the loop you can use regionIds(:)' to make it work with both row and column vectors.
- ~isempty(find(...)) can be simplified to ~any(...).

**Comment by abcdlab-nf** [comment]
Oh yeah, and it might be more flexible to remove the assumption that there are 81924 vertices. CIVET 2 allows for higher resolution surfaces. You could make it numel(regionLabels.idByVertex) instead.

**Comment by Aisa2** [comment]
OK, fixed those things, and took away the input parser since it actually wasn't being used. It can be added back later if we think of some optional arguments.

**Comment by abcdlab-nf** [comment]
Looks good! I tweaked it a little and worked on the documentation.

Is it okay if I remove the following?
- The "fix empty items" code in loadAal78 - this addressed a specific issue with building a cell array of strings and then using strfind/regexp, and it was easy to handle in findRegionIdsByText.
- The excludeAALRegion function - same thing can be done now with "~maskFromRegionIds(aal78, findRegionIdsByText(aal78, 'text'))"
- The makeAALRoi function - same thing can be done now with "maskFromRegionIds(aal78, findRegionIdsByText(aal78, 'text'))"

**Comment by Aisa2** [comment]
Sure, sounds great.

**Comment by abcdlab-nf** [comment]
done! merged to develop

**Pull request merged**
